%{
#include "Lexer.hpp"
#include <string>
#include <sstream>
#undef  YY_DECL
#define YY_DECL int Lexer::yylex()
%}

%option c++
%option noyywrap

%x SC_ARGS
%x SC_TEXT

/* WhiteSpace */
WS      [ \t]+

WORD    [^ \t\n]+

%%

<INITIAL>{WS}           { /* skip leading whitespace */ }

<INITIAL>"/help"        { return static_cast<int>(Token::CMD_HELP);       }
<INITIAL>"/quit"        { return static_cast<int>(Token::CMD_QUIT);       }
<INITIAL>"/disconnect"  { return static_cast<int>(Token::CMD_DISCONNECT); }
<INITIAL>"/users"       { return static_cast<int>(Token::CMD_USERS);      }

<INITIAL>"/connect"     { BEGIN(SC_ARGS); return static_cast<int>(Token::CMD_CONNECT);   }
<INITIAL>"/identify"    { BEGIN(SC_ARGS); return static_cast<int>(Token::CMD_IDENTIFY);  }
<INITIAL>"/status"      { BEGIN(SC_ARGS); return static_cast<int>(Token::CMD_STATUS);    }
<INITIAL>"/msg"         { BEGIN(SC_ARGS); return static_cast<int>(Token::CMD_MSG);       }
<INITIAL>"/pub"         { BEGIN(SC_TEXT); return static_cast<int>(Token::CMD_PUB);       }
<INITIAL>"/newroom"     { BEGIN(SC_ARGS); return static_cast<int>(Token::CMD_NEWROOM);   }
<INITIAL>"/invite"      { BEGIN(SC_ARGS); return static_cast<int>(Token::CMD_INVITE);    }
<INITIAL>"/join"        { BEGIN(SC_ARGS); return static_cast<int>(Token::CMD_JOIN);      }
<INITIAL>"/roomusers"   { BEGIN(SC_ARGS); return static_cast<int>(Token::CMD_ROOMUSERS); }
<INITIAL>"/roomtext"    { BEGIN(SC_ARGS); return static_cast<int>(Token::CMD_ROOMTEXT);  }
<INITIAL>"/leave"       { BEGIN(SC_ARGS); return static_cast<int>(Token::CMD_LEAVE);     }

<INITIAL>"/"[^ \t\n]+   { return static_cast<int>(Token::UNKNOWN_CMD); }
<INITIAL>[^/ \t\n][^\n]* { return static_cast<int>(Token::RAW_TEXT);    }
<INITIAL>\n             { /* empty line */ }
<INITIAL><<EOF>>        { return static_cast<int>(Token::END_OF_INPUT); }

<SC_ARGS>{WS}           { /* skip */ }

<SC_ARGS>{WORD}         { return static_cast<int>(Token::ARG); }
<SC_ARGS>\n             { BEGIN(INITIAL); return static_cast<int>(Token::END_OF_LINE);  }
<SC_ARGS><<EOF>>        { BEGIN(INITIAL); return static_cast<int>(Token::END_OF_INPUT); }

<SC_TEXT>{WS}           { /* skip leading whitespace before body */ }
<SC_TEXT>[^ \t\n][^\n]* { BEGIN(INITIAL); return static_cast<int>(Token::TEXT_BODY);    }
<SC_TEXT>\n             { BEGIN(INITIAL); return static_cast<int>(Token::END_OF_LINE);  }
<SC_TEXT><<EOF>>        { BEGIN(INITIAL); return static_cast<int>(Token::END_OF_INPUT); }

%%

// --- Class Implementation Section ---
// Flex will copy everything below this line directly into the generated .cc file.


Lexer::Lexer(std::istream& in) : yyFlexLexer(&in) {}

void Lexer::setInput(const std::string& line) {
    lineStream_.clear();
    // Appending a newline ensures rules relying on \n or EOF trigger correctly
    lineStream_.str(line + "\n");
    // switch_streams is provided by the yyFlexLexer base class
    switch_streams(&lineStream_, nullptr);
    
    token_ = Token::NONE;
    lexeme_.clear();
}

Token Lexer::nextToken() {
    // yylex() is generated by Flex and executes the rules above
    int raw = yylex();
    
    // YYText() returns the text matched by the active rule
    lexeme_ = YYText();
    token_  = static_cast<Token>(raw);
    
    return token_;
}

const std::string& Lexer::lexeme() const { 
    return lexeme_; 
}

Token Lexer::currentToken() const { 
    return token_; 
}

// Dummy implementation of the base class yylex()
// to satisfy the C++ linker's vtable requirements.
int yyFlexLexer::yylex() {
    return 0;
}

